load goldenimage_result.json into object and print

diff --git a/.github/workflows/goldenimage-workflow.yml b/.github/workflows/goldenimage-workflow.yml
--- a/.github/workflows/goldenimage-workflow.yml
+++ b/.github/workflows/goldenimage-workflow.yml
@@ -117,6 +117,18 @@ jobs:
         run: |
           packer build --only=amazon-ebs.${{ inputs.OS }}_${{ inputs.CPU_ARCH }} -var cpu_arch=${{ inputs.CPU_ARCH }} -var 'tag=${{ env.TAG_NAME }}' -var app=${{ inputs.APP }} -var 'aws_region=${{ inputs.REGION }}' -var 'verbose=${{ env.IS_TEST }}' -var 'base_path=${{ inputs.S3_BASE_PATH }}' -var skip_remote_requirements=true goldenimage.pkr.hcl
 
+      - name: Load parameters from goldenimage_result.json
+        id: load-parameters
+        run: |
+          if [[ ! -f "$GOLDENIMAGE_RESULT_FILE" ]]; then
+            echo "Error: File $GOLDENIMAGE_RESULT_FILE not found!"
+            exit 1
+          fi
+
+          GOLDENIMAGE_RESULT_CONTENT=$(jq '.' "$GOLDENIMAGE_RESULT_FILE")
+
+          echo "$GOLDENIMAGE_RESULT_CONTENT"
+          
       - name: Notify Discord for success
         uses: sarisia/actions-status-discord@v1
         if: success() && vars.WEBHOOK_URL != ''
